version: '2.2'
services:
  web:
    image: joeyntut/advisory.yda
    restart: always
    container_name: ${YDA_SESSION_NAME}-web
    depends_on:
      - mysqldb
    ports:
      - expose_web_port:80
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./.env:/var/www/html/.env
    environment:
      - DB_TYPE=mysql
      - DB_HOST=${YDA_SESSION_NAME}-mysql
      - DB_DATABASE=octobercmsdb
      - DB_USERNAME=root
      - DB_PASSWORD=sql_password

  mysqldb:
    image: mariadb:5.5
    restart: always
    container_name: ${YDA_SESSION_NAME}-mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sql_password
      - MYSQL_DATABASE=octobercmsdb
      - MYSQL_ROOT_HOST=%
